// Mixed read/write benchmark.
//
// The read pool's justification is that searches read through their own
// connections instead of queueing behind the single write connection. A
// search-only benchmark cannot see that: with no writes in flight, one read
// connection is as good as four. This drives writes and searches concurrently
// and reports search latency under write pressure.
//
// Compare the same binary at ENGRAPH_READ_POOL_SIZE=1 and =4. If the pool earns
// its keep, search latency at size 4 should degrade less under writes.
//
// Usage:
//   ENGRAPH_READ_POOL_SIZE=4 ENGRAPH_DATA_DIR=/path/to/lab \
//     cargo run --release -- serve --http --port 8899 --no-auth &
//   node bench/mixed.mjs [port] [seconds]

const PORT = process.argv[2] ?? '8899';
const SECONDS = Number(process.argv[3] ?? 12);
const BASE = `http://127.0.0.1:${PORT}`;

const QUERIES = [
  'embedding latency', 'vector cache', 'graph fusion', 'temporal ranking',
  'sqlite storage', 'concurrency mutex', 'reranker pipeline', 'semantic keyword',
];

async function search(query) {
  const t0 = performance.now();
  const res = await fetch(`${BASE}/api/search`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ query, top_n: 5 }),
  });
  await res.json().catch(() => null);
  return { ms: performance.now() - t0, ok: res.status === 200, status: res.status };
}

// Unique per run. Reusing filenames across runs makes create() fail on
// collision, which silently turns "write pressure" into "rejected-request
// pressure" and invalidates the comparison.
const RUN_ID = `${Date.now().toString(36)}`;

async function write(n) {
  const res = await fetch(`${BASE}/api/create`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      content: `# Bench write ${n}\n\nGenerated by bench/mixed.mjs to create write pressure.\n`,
      filename: `bench-write-${RUN_ID}-${n}`,
    }),
  });
  await res.json().catch(() => null);
  return res.status;
}

const pct = (xs, p) => {
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.min(s.length - 1, Math.floor(s.length * p))];
};
const mean = (xs) => xs.reduce((a, b) => a + b, 0) / xs.length;

async function measureSearches(deadline, label) {
  const times = [];
  let failures = 0;
  let i = 0;
  while (performance.now() < deadline) {
    const r = await search(QUERIES[i++ % QUERIES.length]);
    if (r.ok) times.push(r.ms);
    else failures++;
  }
  return { label, times, failures };
}

const main = async () => {
  for (const q of QUERIES.slice(0, 3)) await search(q);

  // Leg 1: searches with no write pressure.
  const quiet = await measureSearches(performance.now() + SECONDS * 1000, 'quiet');

  // Leg 2: same searches while writes run continuously.
  let writing = true;
  let writeCount = 0;
  let writeFailures = 0;
  const writer = (async () => {
    while (writing) {
      const status = await write(writeCount++);
      if (status !== 200) writeFailures++;
    }
  })();

  const loaded = await measureSearches(performance.now() + SECONDS * 1000, 'under writes');
  writing = false;
  await writer;

  for (const leg of [quiet, loaded]) {
    if (!leg.times.length) {
      console.error(`FAILED: no successful searches in the "${leg.label}" leg`);
      process.exit(1);
    }
  }

  const report = (leg) =>
    `${leg.label.padEnd(12)} n=${String(leg.times.length).padStart(4)}  ` +
    `mean ${mean(leg.times).toFixed(0).padStart(5)}ms  ` +
    `p50 ${pct(leg.times, 0.5).toFixed(0).padStart(5)}ms  ` +
    `p95 ${pct(leg.times, 0.95).toFixed(0).padStart(5)}ms  ` +
    `failures ${leg.failures}`;

  console.log(report(quiet));
  console.log(report(loaded));
  console.log(`writes issued ${writeCount}, write failures ${writeFailures}`);
  if (writeFailures > writeCount * 0.1) {
    console.error(
      `INVALID: ${writeFailures}/${writeCount} writes failed. The "under writes" leg ` +
        `measured rejected requests, not write pressure. Do not compare these numbers.`,
    );
    process.exit(1);
  }
  console.log(
    `search p50 degradation under writes: ` +
      `${(pct(loaded.times, 0.5) / pct(quiet.times, 0.5)).toFixed(2)}x  (1.00x = writes cost readers nothing)`,
  );
};

main().catch((err) => {
  console.error('benchmark failed:', err.message);
  process.exit(1);
});
